version: '3'

services:
  # React App
  web:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run web:dev:docker
    ports:
      - 4201:4200
  

  # Nest App
  api:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run api:dev:docker
    ports:
      - 3334:3333 # API Entry port
      - 9230:9229 # Server Debugging port

volumes:
  mono-node-modules: null